#! /bin/sh

feh --bg-fill ~/walls/wallhaven-2y2wg6.png
polybar &
dunst &
picom &

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         3
bspc config window_gap           6

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#b7bdf8"
bspc config normal_border_color "#24273a"
bspc config focus_follows_pointer true
bspc rule -a feh state=floating
bspc rule -a Polybar layer=above
# bspc rule -a '*' state=floating center=true rectangle=1400x900+0+0


