#! /bin/sh

xwallpaper --zoom $HOME/walls/gruvbox-wallpapers/wallpapers/castle.jpg
$HOME/.config/polybar/launch.sh &
dunst &
picom &

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap           13

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focused_border_color "#98971a"
# bspc config normal_border_color "#1d2021"
bspc config focus_follows_pointer true
bspc rule -a feh state=floating
bspc rule -a Polybar layer=above

